name: GameCI Implementation Test

run-name: ${{ github.actor }} is testing out GameCI Implementation 🚀

on: [push]

jobs:
  Unity-Builder:
    name: Unity Project Builder
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        
      # Cache
      - uses: actions/cache@v3
        with:
          path: My project/Library
          key: Library-My project-Android
          restore-keys: |
            Library-MyProjectName-
            Library-

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android
          projectPath: My project/
          
      #Upload
      - uses: actions/upload-artifact@v3
        with:
          name: Build.apk
          path: build/

      
